viva_ideal_types = {
    "house" : "House",
    "apartment" : "Apartment",
    "cabin" : "Cabin",
    "country-house" : "Country House",
    "castle" : "Castle",
    "commercial-building" : "Commercial building",
    "container" : "Container",
    "cycladic-home" : "Cycladic home",
    "eco-home" : "Eco home",
    "farm" : "Farm",
    "houseboat" : "Houseboat",
    "land" : "Land",
    "mansion" : "Mansion",
    "tiny-home" : "Tiny home",
    "tower" : "Tower",
    "warehouse" : "Warehouse",
    "windmill" : "Windmill",
}

viva_ideal_features = {
    "none" : "None",
    "air-conditioning" : "Air-conditioning",
    "attic" : "Attic",
    "balcony" : "Balcony",
    "basement" : "Basement",
    "bbq" : "BBQ",
    "beach-access" : "Beach access",
    "car-parking" : "Car parking",
    "elevator" : "Elevator",
    "exercise-equipment" : "Exercise Equipment",
    "fire-pit" : "Fire Pit",
    "garage" : "Garage",
    "garden-yard" : "Garden / Yard",
    "heating-system" : "Heating system",
    "home-office" : "Home office",
    "hot-tub" : "Hot Tub",
    "indoor-fireplace" : "Indoor Fireplace",
    "lake-access" : "Lake access",
    "laundry-room" : "Laundry room",
    "outdoor-dining-area" : "Outdoor Dining Area",
    "patio" : "Patio",
    "pool" : "Pool",
    "security-system" : "Security system",
    "ski-in-ski-out" : "Ski-in / Ski-out",
    "solar-panels" : "Solar panels",
    "terrace" : "Terrace",
    "walk-in-closet" : "Walk-in closet",
}